dist: xenial
language: python

python:
  - "3.7"

env:
  - DJANGO=2.2.2

install:
  - pip install django==$DJANGO --quiet
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run runtest.py

after_success:
  coveralls
